{{- if .Values.reflex }}
apiVersion: v1
{{- include "coelho-realtime.ConfigMapSettings" (dict "appName" "reflex" "root" .) | nindent 0}}
data:
  {{- include "coelho-realtime.commonEnvVars" . | nindent 2 }}
  # Reflex configuration using Skaffold port-forward
  REFLEX_REDIS_URL: "redis://coelho-realtime-redis-master:6379"
  REFLEX_API_URL: "http://localhost:8000"
  REFLEX_BACKEND_HOST: "0.0.0.0"
  REFLEX_BACKEND_PORT: "8000"
  REFLEX_FRONTEND_PORT: "3000"
  REFLEX_DEPLOY_URL: "http://localhost:3000"
  REFLEX_ENV: "DEV" #"PROD"
{{- end }}
