{{- if and .Values.river (index .Values "kube-prometheus-stack" "enabled") }}
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: {{ .Release.Name }}-river
  namespace: {{ .Release.Namespace }}
  labels:
    app: coelho-realtime-river
    release: {{ .Release.Name }}
spec:
  selector:
    matchLabels:
      app: coelho-realtime-river
  namespaceSelector:
    matchNames:
      - {{ .Release.Namespace }}
  endpoints:
    - port: http
      interval: 30s
      path: /metrics
      scheme: http
{{- end }}
