apiVersion: v1
kind: Service
metadata:
  name: coelho-realtime-mlflow-service
  labels:
    app: coelho-realtime-mlflow-deployment
  namespace: default
spec:
  selector:
    app: coelho-realtime-mlflow-deployment
  ports:
    - name: http
      port: 5000
      targetPort: 5000
      protocol: TCP
  type: ClusterIP
