apiVersion: v1
kind: ConfigMap
metadata:
  name: coelho-realtime-streamlit-configmap
data:
  NODE_ENV: "production"
  OPENAI_API_KEY: "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"
  EVAGPT_TOKEN: "zpka_b54ee251e24f479b88f16e7a96840690_703fa1be"
  EVAGPT_CONVERSATION_ID: "zw5acqgr7p9mcdl64866ztjh"
  AWS_ACCESS_KEY_ID: "AKIASVQEL7DJW4LA7UXN"
  AWS_SECRET_ACCESS_KEY: "Vell8rAYaYLeMMnsCQmVL5WSqKViJbWKYPbTc9rib"
  AWS_REGION: "sa-east-1"
  GOOGLE_APPLICATION_CREDENTIALS: "/app/gcp-credentials.json"
  GOOGLE_CLOUD_PROJECT: "ambiente-de-demonstracao-xvia"
  FASTAPI_HOST: "speech-to-speech-fastapi-service"
  GRAFANA_HOST: "speech-to-speech-grafana-service"
  PROMETHEUS_HOST: "speech-to-speech-prometheus-service"
  STREAMLIT_HOST: "speech-to-speech-streamlit-service"
