apiVersion: apps/v1
kind: Deployment
metadata:
  name: coelho-realtime-mlflow-deployment
  namespace: coelho
  labels:
    app: coelho-realtime-mlflow-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: coelho-realtime-mlflow-deployment
  template:
    metadata:
      labels:
        app: coelho-realtime-mlflow-deployment
    spec:
      containers:
      - name: coelho-realtime-mlflow-container
        image: coelho-realtime-mlflow
        imagePullPolicy: IfNotPresent #Always
        ports:
        - containerPort: 5000
        envFrom:
          - configMapRef:
              name: coelho-realtime-mlflow-configmap
        #volumeMounts:
        #- name: mlflow-app
        #  mountPath: /mlflow-data
        resources:
          requests:
            memory: "512Mi"
            cpu: "250m"
          limits:
            memory: "1Gi"
            cpu: "500m"
        livenessProbe:
          httpGet:
            path: /health
            port: 5000
          initialDelaySeconds: 30
          periodSeconds: 15
          timeoutSeconds: 30
          failureThreshold: 5
        readinessProbe:
          httpGet:
            path: /health
            port: 5000
          initialDelaySeconds: 30
          periodSeconds: 15
          timeoutSeconds: 30
          failureThreshold: 5
      #volumes:
      #- name: mlflow-app
      #  persistentVolumeClaim:
      #    claimName: coelho-realtime-mlflow-pvc