apiVersion: apps/v1
kind: Deployment
metadata:
  name: coelho-realtime-streamlit-deployment
  namespace: coelho
spec:
  replicas: 1
  selector:
    matchLabels:
      app: coelho-realtime-streamlit-deployment
  template:
    metadata:
      labels:
        app: coelho-realtime-streamlit-deployment
    spec:
      containers:
      - name: coelho-realtime-streamlit-container
        image: coelho-realtime-streamlit
        imagePullPolicy: IfNotPresent #Always
        ports:
        - containerPort: 8501
        #volumeMounts:
        #- name: streamlit-app
        #  mountPath: /streamlit-data
        resources:
          requests:
            memory: "256Mi"
            cpu: "125m"
          limits:
            memory: "512Mi"
            cpu: "250m"
      #volumes:
      #- name: streamlit-app
      #  persistentVolumeClaim:
      #    claimName: coelho-realtime-streamlit-pvc