apiVersion: apps/v1
kind: Deployment
metadata:
  name: coelho-realtime-kafka-deployment
  labels:
    app: coelho-realtime-kafka-deployment
  namespace: default
spec:
  replicas: 1
  selector:
    matchLabels:
      app: coelho-realtime-kafka-deployment
  template:
    metadata:
      labels:
        app: coelho-realtime-kafka-deployment
    spec:
      containers:
      - name: coelho-realtime-kafka-container
        image: kafka_app:latest
        imagePullPolicy: Always
        ports:
        - containerPort: 9092
        - containerPort: 29092
        - containerPort: 9093
        envFrom:
        - configMapRef:
            name: coelho-realtime-kafka-configmap
        volumeMounts:
        - name: kafka-data
          mountPath: /opt/bitnami/kafka/data
        - name: shared-workspace
          mountPath: /opt/workspace
        resources:
          requests:
            memory: "512Mi"
            cpu: "250m"
          limits:
            memory: "1Gi"
            cpu: "500m"
      volumes:
      - name: kafka-data
        persistentVolumeClaim:
          claimName: coelho-realtime-kafka-pvc
      - name: shared-workspace
        persistentVolumeClaim:
          claimName: shared-workspace-pvc