---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: coelho-realtime-fastapi-deployment
  namespace: coelho
  labels:
    app: coelho-realtime-fastapi-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: coelho-realtime-fastapi-deployment
  template:
    metadata:
      labels:
        app: coelho-realtime-fastapi-deployment
    spec:
      containers:
        - name: coelho-realtime-fastapi-container
          image: coelho-realtime-fastapi
          imagePullPolicy: IfNotPresent #Always
          envFrom:
            - configMapRef:
                name: coelho-realtime-fastapi-configmap
          livenessProbe:
            httpGet:
              path: /health
              port: 8000
            initialDelaySeconds: 60  # Wait 1 minute for startup
            periodSeconds: 30      # Check every 30 seconds
            failureThreshold: 3    # Restart after 3 failures (90 seconds of unresponsiveness)
          resources:
            requests:
              memory: "512Mi"
              cpu: "300m"
            limits:
              memory: "1536Mi"
              cpu: "750m"
          #env:
          #- name: AWS_ACCESS_KEY_ID_STS
          #  valueFrom:
          #    secretKeyRef:
          #      name: coelho-realtime-secrets          # ← Created by kubectl command
          #      key: aws-access-key-id-sts               # ← Key from --from-literal
      #dnsPolicy: ClusterFirst
      #dnsConfig:
      #  nameservers:
      #    - 8.8.8.8
      #    - 1.1.1.1