apiVersion: v1
kind: Service
metadata:
  name: coelho-realtime-fastapi-service
  namespace: coelho
  labels:
    app: coelho-realtime-fastapi-deployment
spec:
  selector:
    app: coelho-realtime-fastapi-deployment
  ports:
    - name: http
      port: 8000
      targetPort: 8000
      protocol: TCP
  type: LoadBalancer #ClusterIP
