apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: coelho-realtime-fastapi-ingress
  namespace: default
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /
spec:
  rules:
  - host: coelho-realtime-fastapi.local
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: coelho-realtime-fastapi-service
            port:
              number: 8000