apiVersion: v1
{{- include "coelho-realtime.ConfigMapSettings" (dict "appName" "kafka") | nindent 0}}
data:
  # Kafka-specific configuration
  ALLOW_PLAINTEXT_LISTENER: "yes"
  KAFKA_CFG_ADVERTISED_LISTENERS: "CLIENT_INTERNAL://coelho-realtime-kafka-service:29092,CLIENT_EXTERNAL://localhost:9092"
  KAFKA_CFG_NODE_ID: "1"
  KAFKA_CFG_PROCESS_ROLES: "controller,broker"
  KAFKA_CFG_CONTROLLER_QUORUM_VOTERS: "1@coelho-realtime-kafka-service:9093"
  KAFKA_CFG_LISTENERS: "CLIENT_INTERNAL://:29092,CLIENT_EXTERNAL://:9092,CONTROLLER://:9093"
  KAFKA_CFG_LISTENER_SECURITY_PROTOCOL_MAP: "CLIENT_INTERNAL:PLAINTEXT,CLIENT_EXTERNAL:PLAINTEXT,CONTROLLER:PLAINTEXT"
  KAFKA_CFG_CONTROLLER_LISTENER_NAMES: "CONTROLLER"
  KAFKA_CFG_INTER_BROKER_LISTENER_NAME: "CLIENT_INTERNAL"
  # Don't forget to remove the CLIENT_EXTERNAL listener in production
  # Correct PLAINTEXT settings when in production (security vulnerability)

  # Common service hosts
  {{- include "coelho-realtime.commonEnvVars" . | nindent 2 }}
