{{- if .Values.streamlit.enabled }}
apiVersion: v1
{{- include "coelho-realtime.ConfigMapSettings" (dict "appName" "streamlit" "root" .) | nindent 0}}
data:
  {{- include "coelho-realtime.commonEnvVars" . | nindent 2 }}
{{- end }}
